include:
  - project: devsecops/cicd/pipeline
    ref: v18.0.6
    file: main.yml

variables:
  PIP_INDEX_URL: https://devpi.lion.act3-ace.ai/root/pypi/+simple/
  SRC_DIR: "run_time_assurance"
  ACT3_SECRETS_AUTH_TOML: $POETRY_AUTH_TOML

build image:
  variables:
    TARGET_STAGE: cicd

build tagged image:
  variables:
    TARGET_STAGE: build
    DESTINATION_PATH: /releases

build development image:
  extends: build tagged image
  variables:
    TARGET_STAGE: develop
    DESTINATION_PATH: /development/$TARGET_STAGE

build package image:
  extends: build tagged image
  variables:
    TARGET_STAGE: package
    DESTINATION_PATH: /releases/$TARGET_STAGE

# Overriding mkdocs because the ci-mkdocs image does not have gcc and we need that to install quadprog
mkdocs:
  needs: [ "build image" ]
  image:
    name: $CI_REGISTRY_IMAGE/cicd:ci-$CI_PIPELINE_ID
    entrypoint: ['']
  variables:
    MKDOCS_PDF_EXPORT: 1
  script:
    - mkdocs build
  artifacts:
    paths:
      - site/

# Currently no unit tests, so we're disablig the unit test job
python unit test:
  rules:
    - when: never
  variables:
    UNIT_TEST_DIR: tests
  script:
    - ls

