#--------------------------------------------------------------------------
#Air Force Research Laboratory (AFRL) Autonomous Capabilities Team (ACT3)
#Reinforcement Learning (RL) Core  Extension.
#
#This is a US Government Work not subject to copyright protection in the US.
#
#The use, dissemination or disclosure of data in this file is subject to
#limitation or restriction. See accompanying README and LICENSE for details.
#---------------------------------------------------------------------------
site_name: Run-Time-Assurance
site_author: Safe-Autonomy Team
repo_url: https://github.com/act3-ace/run-time-assurance
docs_dir: "docs"
site_url: https://github.com/act3-ace/
edit_uri: blob/main/docs/
site_dir: site
site_description: "The Run Time Assurance library provides implementations of various RTA methods"

exclude_docs:
  __init__.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
  - autorefs
  - gen-files:
      scripts:
        - docs/gen_ref_nav.py  # or any other name or path
  - section-index
  - pdf-export:
      verbose: false
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
      combined: true


theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
  - navigation.tabs
  - navigation.top
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode


extra_css:
  - css/style.css
  - css/material.css
  - css/mkdocstrings.css


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.arithmatex:  # MathJax (latex)
      generic: true

extra_javascript:
  - https://unpkg.com/mermaid@8.4.2/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - "Introduction": index.md
  - "Installation": install.md
  - "Concepts":
    - RTA/index.md
    - "Defining Safety": RTA/safety.md
    - "Simplex RTA Filters": 
      - RTA/simplex.md
      - "Explicit Simplex": RTA/explicit_simplex.md
      - "Implicit Simplex": RTA/implicit_simplex.md
    - "ASIF RTA Filters":
      - RTA/asif.md
      - "Explicit ASIF": RTA/explicit_asif.md
      - "Implicit ASIF": RTA/implicit_asif.md
      - "Discrete ASIF": RTA/discrete_asif.md
  - "Usage": usage.md
  - "Developers Guide": developer-guide.md
  - "API":
    - api/index.md
    - constraint: api/constraint.md
    - controller: api/controller.md
    - rta:
      - api/rta/index.md
      - asif: api/rta/asif.md
      - base: api/rta/base.md
      - simplex: api/rta/simplex.md
    - state: api/state.md
    - utils: 
      - api/utils/index.md
      - utils: api/utils/utils.md
      - api/utils/sample_testing.md
    - zoo:
      - api/zoo/index.md
      - cwh:
        - api/zoo/cwh/index.md
        - api/zoo/cwh/docking_2d.md
        - api/zoo/cwh/docking_3d.md
        - api/zoo/cwh/inspection_1v1.md
        - api/zoo/cwh/inspection_3d.md
        - api/zoo/cwh/random_sample_testing.md
      - integrators:
        - api/zoo/integrators/index.md
        - api/zoo/integrators/integrator_1d.md
